name: Final Sempurna
on:
  schedule:
    - cron: '*/30 0-22 * * 1-5'
  workflow_dispatch:
jobs:
  final:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
      - run: pip install requests pandas yfinance pytz
      - env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python kerajaan_semut_emas_final_sempurna.py
