name: TANI V8
on:
  schedule:
    - cron: '0,30 * * * *'  # tiap 30 menit biar tenaga keisi
  workflow_dispatch:
jobs:
  tani:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install requests pandas yfinance pytz
      - run: kerajaan_semut_emas_tani_v8_2_cakep.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
